update linglong.yaml
linglongdev/Repository-Manager pull request #10
Opened 2024-07-09 07:08 UTC by Charlie-doggy

a photo tool libre

2024-07-09 07:09 UTC, Charlie-doggy commented
![Uploading 下载.png…]()

2024-07-09 07:11 UTC, Charlie-doggy commented
![Uploading 下载.png…]()

2024-07-09 07:11 UTC, Charlie-doggy commented
![Uploading 下载.png…]()

2024-07-09 07:17 UTC, Charlie-doggy commented
![Uploading 下载.png…]()

2024-07-09 07:17 UTC, Charlie-doggy commented
![image](https://github.com/linglongdev/Repository-Manager/assets/174567485/fedd0c93-b3b6-4c50-9940-ba03b69fbd4d)

2024-07-29 07:23 UTC, myml requested changes
这个仓库只用户创建其他应用仓库, 不应该把linglong.yaml上传本仓库

2024-09-12 06:10 UTC, closed without merging